version: '3'
services:
  dev:
    container_name: strapi-ts-dev
    build:
      context: .
      target: development
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./app:/srv/app
      - /usr/src/app/node_modules
    ports:
      - '1337:1337'
    command: yarn dev
    env_file:
      - ./strapi/.env.development
    networks:
      - strapi-ts-network
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    networks:
      - strapi-ts-network
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - db:/data/db

  docs:
    container_name: strapi-ts-docs
    build:
      target: development
      context: ./docs
    volumes:
      - ./docs:/usr/srv/docs
      - /usr/srv/docs/node_modules
    ports:
      - '4000:80'
    networks:
      - strapi-ts-network
    command: yarn start --port 80 --host 0.0.0.0

networks:
  strapi-ts-network:

volumes:
  db:
