/**
 * This file is auto-generated by "../esbuild/strapiRunTimeDts.ts"
 */

declare type IApiNames = 'category' | 'product';

declare type IPolicies =
  | 'plugins::users-permissions.ratelimit'
  | 'plugins::users-permissions.isAuthenticated'
  | 'plugins::users-permissions.is-registration';
